<!DOCTYPE html>
<html>
<head>
    <title>{{hostname}} - Detailed VM Inspection Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 20px;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            overflow: hidden;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }
        .header h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
        }
        .content {
            padding: 40px;
        }
        .section {
            margin-bottom: 30px;
            padding: 25px;
            background: #f8f9fa;
            border-radius: 8px;
            border-left: 4px solid #667eea;
        }
        .section h2 {
            color: #667eea;
            margin-bottom: 20px;
            font-size: 1.8em;
        }
        .info-grid {
            display: grid;
            grid-template-columns: 200px 1fr;
            gap: 15px;
            margin: 15px 0;
        }
        .label {
            font-weight: 600;
            color: #555;
            text-transform: uppercase;
            font-size: 0.85em;
            letter-spacing: 0.5px;
        }
        .value {
            color: #333;
            font-size: 1.1em;
            padding: 5px 10px;
            background: white;
            border-radius: 4px;
        }
        .badge {
            display: inline-block;
            padding: 5px 15px;
            background: #667eea;
            color: white;
            border-radius: 20px;
            font-size: 0.9em;
            margin-right: 10px;
        }
        .footer {
            background: #2c3e50;
            color: white;
            padding: 30px;
            text-align: center;
        }
        .footer strong {
            color: #667eea;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🖥️ VM Inspection Report</h1>
            <p><span class="badge">{{hostname}}</span></p>
        </div>

        <div class="content">
            <div class="section">
                <h2>📋 System Overview</h2>
                <div class="info-grid">
                    <div class="label">Hostname</div>
                    <div class="value">{{hostname}}</div>

                    <div class="label">Operating System</div>
                    <div class="value">{{os_type}}</div>

                    <div class="label">Distribution</div>
                    <div class="value">{{distribution}}</div>

                    <div class="label">Version</div>
                    <div class="value">{{version}}</div>

                    <div class="label">Architecture</div>
                    <div class="value">{{architecture}}</div>
                </div>
            </div>

            <div class="section">
                <h2>ℹ️ Report Information</h2>
                <div class="info-grid">
                    <div class="label">Generated By</div>
                    <div class="value">{{tool_name}} v{{tool_version}}</div>

                    <div class="label">Timestamp</div>
                    <div class="value">{{timestamp}}</div>
                </div>
            </div>
        </div>

        <div class="footer">
            <p>Powered by <strong>{{tool_name}}</strong> - Pure Rust VM Inspection Toolkit</p>
            <p style="margin-top: 10px; font-size: 0.9em; opacity: 0.8;">{{timestamp}}</p>
        </div>
    </div>
</body>
</html>
