<!DOCTYPE html>
<html>
<head>
    <title>{{hostname}} - Inspection Report</title>
    <style>
        body { font-family: sans-serif; margin: 20px; }
        h1 { color: #333; }
        .info { margin: 10px 0; }
    </style>
</head>
<body>
    <h1>VM Inspection Report</h1>
    <div class="info"><strong>Hostname:</strong> {{hostname}}</div>
    <div class="info"><strong>OS:</strong> {{os_type}}</div>
    <div class="info"><strong>Distribution:</strong> {{distribution}}</div>
    <div class="info"><strong>Version:</strong> {{version}}</div>
    <div class="info"><strong>Architecture:</strong> {{architecture}}</div>
    <hr>
    <p><small>Generated by {{tool_name}} v{{tool_version}} on {{timestamp}}</small></p>
</body>
</html>
