<!DOCTYPE html>
<html>
<head>
    <title>{{hostname}} - VM Inspection Report</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            background: #f5f5f5;
        }
        .container {
            max-width: 900px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        h1 {
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }
        h2 {
            color: #34495e;
            margin-top: 25px;
        }
        .info-grid {
            display: grid;
            grid-template-columns: 150px 1fr;
            gap: 10px;
            margin: 20px 0;
        }
        .label {
            font-weight: bold;
            color: #555;
        }
        .value {
            color: #333;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #777;
            font-size: 0.9em;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🖥️ VM Inspection Report</h1>

        <h2>System Information</h2>
        <div class="info-grid">
            <div class="label">Hostname:</div>
            <div class="value">{{hostname}}</div>

            <div class="label">OS Type:</div>
            <div class="value">{{os_type}}</div>

            <div class="label">Distribution:</div>
            <div class="value">{{distribution}}</div>

            <div class="label">Version:</div>
            <div class="value">{{version}}</div>

            <div class="label">Architecture:</div>
            <div class="value">{{architecture}}</div>
        </div>

        <div class="footer">
            Generated by {{tool_name}} v{{tool_version}}<br>
            {{timestamp}}
        </div>
    </div>
</body>
</html>
