# 🖥️ VM Inspection Report: {{hostname}}

**Generated:** {{timestamp}}

---

## 📋 System Information

| Property | Value |
|----------|-------|
| **Hostname** | {{hostname}} |
| **OS Type** | {{os_type}} |
| **Distribution** | {{distribution}} |
| **Version** | {{version}} |
| **Architecture** | {{architecture}} |

---

## ℹ️ Report Details

- **Tool:** {{tool_name}} v{{tool_version}}
- **Timestamp:** {{timestamp}}

---

*Generated by {{tool_name}} - Pure Rust VM Inspection Toolkit*
