# 🖥️ VM Inspection Report

![OS](https://img.shields.io/badge/OS-{{os_type}}-blue)
![Distribution](https://img.shields.io/badge/Distribution-{{distribution}}-green)
![Architecture](https://img.shields.io/badge/Architecture-{{architecture}}-orange)

**Generated:** {{timestamp}}

---

## 📑 Table of Contents

- [System Overview](#system-overview)
- [Operating System](#operating-system)
- [Report Information](#report-information)

---

## 📋 System Overview

```
╔══════════════════════════════════════════════════════════╗
║              VM: {{hostname}}
║  OS: {{os_type}} {{distribution}} {{version}}
║  Architecture: {{architecture}}
╚══════════════════════════════════════════════════════════╝
```

---

## 💻 Operating System

### Core Information

| Property | Value |
|----------|-------|
| **Hostname** | `{{hostname}}` |
| **OS Type** | `{{os_type}}` |
| **Distribution** | `{{distribution}}` |
| **Version** | `{{version}}` |
| **Architecture** | `{{architecture}}` |

---

## ℹ️ Report Information

### Generation Details

- **Tool Name:** {{tool_name}}
- **Tool Version:** {{tool_version}}
- **Generated:** {{timestamp}}

---

## 📊 System Diagram

```mermaid
graph TB
    VM["{{hostname}}<br/>Virtual Machine"]
    OS["Operating System<br/>{{os_type}} {{distribution}} {{version}}"]
    ARCH["Architecture<br/>{{architecture}}"]

    VM --> OS
    OS --> ARCH
```

---

*Generated by **{{tool_name}}** v{{tool_version}} - Pure Rust VM Inspection Toolkit*

> **Note:** This is a detailed template with enhanced formatting and diagrams.
