VM INSPECTION REPORT
====================

Hostname:     {{hostname}}
OS:           {{os_type}}
Distribution: {{distribution}}
Version:      {{version}}
Architecture: {{architecture}}

Generated by {{tool_name}} v{{tool_version}} on {{timestamp}}
